In [1]:
from sklearn.linear_model import LogisticRegression,LinearRegression
import numpy as np
import pandas as pd
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets  import load_digits
from sklearn.model_selection import train_test_split

In [37]:
digits=load_digits()
X=digits.data
y=digits.target



In [41]:
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.3)

## Logistic Regression

## Support Vector Machines

In [45]:
svm=SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

C:\Users\User\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.37407407407407406

## Random Forest

In [49]:
randomforest=RandomForestClassifier(n_estimators=40)
randomforest.fit(X_train,y_train)
randomforest.score(X_test,y_test)

0.9851851851851852

In [59]:
from sklearn.model_selection import KFold
folds=KFold(n_splits=3)
type(folds)

sklearn.model_selection._split.KFold

In [58]:
for i,y in folds.split([44,55,66,77,88,99,123,456,678,999]):
    print(i)

[4 5 6 7 8 9]
[0 1 2 3 7 8 9]
[0 1 2 3 4 5 6]


In [61]:
from sklearn.model_selection import cross_val_score

In [69]:
np.average(cross_val_score(LogisticRegression(),digits.data,digits.target))

C:\Users\User\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Def

0.9182204459698582

In [71]:
np.average(cross_val_score(SVC(),digits.data,digits.target))

C:\Users\User\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 

0.4213679084629655

In [72]:
np.average(cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target))

C:\Users\User\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


0.9382097992257531

In [73]:
np.average(cross_val_score(RandomForestClassifier(n_estimators=10),digits.data,digits.target))

C:\Users\User\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


0.9003988161449885

In [74]:
np.average(cross_val_score(RandomForestClassifier(n_estimators=100),digits.data,digits.target))

C:\Users\User\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


0.9409866121839645

In [75]:
np.average(cross_val_score(RandomForestClassifier(n_estimators=200),digits.data,digits.target))

C:\Users\User\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


0.9426588065191684